name: Build binaries

on:
  workflow_call:
    inputs:
      publish-tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      publish-tag:
        required: true
        type: string

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload-binary:
    name: Build ${{ matrix.target }}
    strategy:
      matrix:
        include:
        - target: aarch64-apple-darwin
          os: macos-latest
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: x86_64-pc-windows-msvc
          os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - uses: moonrepo/setup-rust@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: client,server
        target: ${{ matrix.target }}
        ref: refs/tags/${{ inputs.publish-tag }}
        tar: all
        zip: windows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
        CARGO_PROFILE_RELEASE_LTO: true
