name: Release

on:
  workflow_dispatch:
    inputs:
      publish-tag:
        description: 'The tag to publish'
        required: true
        type: string

concurrency:
  group: release

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Install Rust toolchain
      uses: moonrepo/setup-rust@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check and Test
      run: cargo check --all-targets --all-features && cargo test

    - name: Tag the version
      env:
        GIT_TAG: ${{ inputs.publish-tag }}
      run: |
        git tag "${GIT_TAG}"
        git push origin "${GIT_TAG}"

    - name: Generate a changelog
      uses: orhun/git-cliff-action@v4
      id: git-cliff
      with:
        config: cliff.toml
        args: -vv --latest --strip header
      env:
        OUTPUT: CHANGES.md
        GITHUB_REPO: ${{ github.repository }}

    - name: Create github release
      uses: taiki-e/create-gh-release-action@v1
      with:
        branch: main
        changelog: CHANGES.md
        ref: refs/tags/${{ inputs.publish-tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-binary:
    name: Run the build-binaries workflow
    needs:
    - create-release
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-binaries.yaml
    with:
      publish-tag: ${{ inputs.publish-tag }}
